name: CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "public/**"
      - "next.config.ts"
      - "package.json"
      - "tsconfig.json"
      - "postcss.config.*"
      - "eslint.config.*"
      - "vercel.json"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "public/**"
      - "next.config.ts"
      - "package.json"
      - "tsconfig.json"
      - "postcss.config.*"
      - "eslint.config.*"
      - "vercel.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run build
        run: npm run build